version: "3.2"
services:
  web:
    image: pchico83/ci
    build:
      cache_from: # Image to be used as cache memory for the next docker operations
        - pchico83/ci
      context: .
    depends_on:
      - redis
    ports:
      - 5000:5000
  redis:
    image: redis
